### ISSUE TITLE
emptyLineBefore property among declaration order

### ISSUE THREAD

**Issue by KefDS** [ream88/stylelint-config-idiomatic-order#4]
Hi, thanks for the package, it's very useful.

Now, I would want my _declaration order_ to be separated by an empty line, like the example of [idiomatic-css](https://github.com/necolas/idiomatic-css)

```css
.selector {
    position: absolute;
    z-index: 10;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;

    display: inline-block;
    overflow: hidden;
    box-sizing: border-box;
    width: 100px;
    height: 100px;
    padding: 10px;
    border: 10px solid #333;
    margin: 10px;

    background: #000;
    color: #fff;
    font-family: sans-serif;
    font-size: 16px;
    text-align: right;
}
```

Is there a way to do that?
Thanks.
